### ISSUE TITLE
CSS value 'initial' not valid in IE11

### ISSUE THREAD

**Issue by endloop-dev** [endloop-dev/endloop-css#2]
Solution: instead of `initial`, the following class needs the value `0px` to render correctly in IE11:

**Problem:**
```css
.flex-row + .flex-row {
    padding-top: initial;
    padding-bottom: initial;
}
````

**Corrected:**
```css
.flex-row + .flex-row {
    padding-top: 0px;
    padding-bottom: 0px;
}
````
